#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=move_and_cat
#SBATCH --mail-type=BEGIN,END
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=20g
#SBATCH --time=00:10:00
#SBATCH --account=bfoxman0
#SBATCH --partition=standard
#SBATCH --output=concatenation.log

#source activate biobakery
./moveAndcat.sh
